# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          wget https://www.uupdump.net/get.php?id=43179438-8021-401a-9fff-2f85f35aa946&pack=zh-cn&edition=professional
          sudo apt-get install unzip
          unzip *.zip
          bash uup_download_linux.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          rename *.iso Windows10-Dev-master.iso
          
      - uses: majkrzak/create-release@master
        with:
            token: ${{secrets.RELEASES_TOKEN}}
            name: windows10 msater
            code: latest
            prerelease: true
            assets: >
                    Windows10-Dev-master.iso:Windows10-Dev-master.iso
            

